spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
server :
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui/html

keycloak:
  realm: royaume-product
  resource: client-royaume
  auth-server-url: http://localhost:30100/auth
  public-client: false
  bearer-only : true